server:
  port: 8000
  servlet:
    context-path: /
  shutdown: graceful   # 优雅停服务，在容器关闭时，web服务器将不再接收新请求，并将等待活动请求完成的缓冲期。从springboot2.3.0引入的新特性
spring:
  application:
    name: sc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: sc-provider
          uri: la://nutcracker:8848
          predicates:
            - Path=/aplus-support-web/**
            - Method=POST,GET
          filters:
            - AddResponseHeader=From-Host,127.0.0.1:8882
logging:
  pattern:
    console: "[%date{HH:mm:ss.SSS}] [%thread] %-5level %logger %line - %msg%n"
  level:
    root: INFO
    org.nutcracker: DEBUG
    org.springframework.web: TRACE
    org.springframework.http: TRACE
    org.springframework.security: TRACE
    org.springframework.cloud.gateway: TRACE
    org.springframework.security.jwt: TRACE
#    org.springframework.jdbc.core.JdbcTemplate: DEBUG
#    org.springframework.jdbc.core.StatementCreatorUtils: trace
#    org.apache.ibatis.jdbc.ScriptRunner: DEBUG
#    java.sql.Connection: DEBUG
#    java.sql.Statement: DEBUG
#    java.sql.PreparedStatement: DEBUG
